### ISSUE TITLE
Use higher ress tiffs to do climate matching

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/riparias-prep#1]
https://ndownloader.figshare.com/files/12407516 => download 1x1km tiffs 0p0083 (niet conf)
https://www.rdocumentation.org/packages/tiff/versions/0.1-6/topics/readTIFF => to read tiffs
The maps are stored in GeoTIFF format as unsigned 8-bit integers. The maps are referenced to the World Geodetic Reference System 1984 (WGS 84).

_Originally posted by @SanderDevisscher in https://github.com/inbo/easin/issues/39#issuecomment-809377485_

**Comment by SanderDevisscher** [comment]
@adrienlatli @timadriaens I'll continue improving the koppen geiger climate matching in this public repo

**Comment by timadriaens** [comment]
Am posting the last comment from Adrien here: 

Hi all,

We discuss with Romain of the climate matching results.

According to the (pre) list of the 32 crayfish available in e-shops, 4 species are included in the climate matching list (actual climate) and 13 species are included in the climate matching (futur).

3 species available in e-shop have not been analysed with climate matching approach (species not included in my initial list : Cherax communis, Cherax snowden et Procambarus ouachitae).

Students will begin soon the shop inventory to get the most complete crayfish list available in market.

Pending the complete taxonomic list, would it be useful to carry out the climate matching analysis on all the crayfish species available in the GBIF database ?

Best
Adrien

**Comment by SanderDevisscher** [comment]
> 3 species available in e-shop have not been analysed with climate matching approach (species not included in my initial list : Cherax communis, Cherax snowden et Procambarus ouachitae).

These can be added to [White list proposal for aquarium crayfish GBIF 22092020.xlsx](https://github.com/inbo/riparias-prep/blob/1_climate_matching_rework/data/raw/White%20list%20proposal%20for%20aquarium%20crayfish%20GBIF%2022092020.xlsx) in the `1_climate_matching_rework` - branch

> Pending the complete taxonomic list, would it be useful to carry out the climate matching analysis on all the crayfish species available in the GBIF database ?

If you would provide me with a list of crayfish families (example https://www.gbif.org/species/8670) to consider with the corresponding taxonkeys I can do a gbif download based on this. 

=> firstly however I would like to focus on the rework for the higher resolution raster files. I'll open a new issue for this analysis.

**Comment by timadriaens** [comment]
Indeed, best to focus on the workflow first so it can include the updated KG climate maps from the [Beck et al. paper](https://www.nature.com/articles/sdata2018214)) as wel will also use this for the aquatic plants later.

**Comment by SanderDevisscher** [comment]
@timadriaens in hindsight a 1x1km worldwide grid seems a bit overkill. I suggest we switch to 10x10km instead ?

**Comment by timadriaens** [comment]
the belgian risk map workflow also uses 1km. The point is of course also that a greater resolution increases the error rate when assigning a record to a grid cell (with this crude climate matching, we don't even take into account uncertainty on the coordinates). So I am ok with 10km (but I wonder about the previous map because it didn't have the right climatic zones for Belgium). Perhaps @adrienlatli has an opinion on the matter?

**Comment by adrienlatli** [comment]
If the belgian risk map workflow uses 1km accuracy it 's maybe better to keep the same scale for potential future publications.

But if the climate matching workflow 1x1km is too time expensive, let's go to the 10x10km, I'm pretty sure it's good enough.

**Comment by timadriaens** [comment]
OK! I agree with that. The climate matching is only meant to selection potential species for in depth RA so certainly a good approach.
