### ISSUE TITLE
Get other scenarios + Rewrite CM

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/riparias-prep#23]
> @RomainWilleput can you provide a working link to the different scenarios?

For some reason, the link only works from my university's wifi network (but not from my home)
Here are the available datasets:
![IMG_20210510_124718](https://user-images.githubusercontent.com/81576915/117648223-3fdf4000-b18e-11eb-91bb-64fc8a7c6c62.jpg)

If it seems useful, I can try to download them at the university and then send them to you.

_Originally posted by @RomainWilleput in https://github.com/inbo/riparias-prep/discussions/19#discussioncomment-717849_

**Comment by SanderDevisscher** [comment]
The following steps need to be undertaken:
- [ ] @RomainWilleput downloads the scenarios & sends these to @SanderDevisscher or uploads them directly to a new branch
- [ ] @SanderDevisscher rewrites the crayfish & plants cm scripts

**Comment by RomainWilleput** [comment]
I will send you all datasets tonight from my computer, I only have my phone now

**Comment by RomainWilleput** [comment]
[Maps Koppen Geiger.zip](https://github.com/inbo/riparias-prep/files/6454048/Map.Koppen.Geiger.zip)
These are the Koppen-Geiger cards.
The future maps are according to the A1FI scenario.
Can you confirm me that this is ok for you?

**Comment by SanderDevisscher** [comment]
`23_New_Scenarios` - branch

**Comment by SanderDevisscher** [comment]
@RomainWilleput What do we do with records between 2001- today ? In the current sorting of scenarios 2001 - 2025 is a future scenario.

**Comment by SanderDevisscher** [comment]
Flow rework suggestion:
![CM_flow](https://user-images.githubusercontent.com/16779320/117975725-4527c080-b32f-11eb-9ec0-371e5bd01048.png)

This would result in the following steps:
- [ ] Upload observed shapes to ./data/spatial/koppen-geiger/observed/
- [ ] Upload future scenario shapes to ./data/spatial/koppen-geiger/future/
- [ ] Create a script to calculate belgian future KG codes
- [ ] Add rerun option for new script to CM script. 
- [ ] Rework CM - script to assign climate to obs according to observation date & resp. observed scenario
- [ ] Rework CM - script to read future scenarios & use these to filter species list

**Comment by RomainWilleput** [comment]
The maps I sent you are from Rubel & Kottek 2010.
We can use the "observed" maps for occurrences from 1950 to 2000.

Then I think we have several possibilities:
- Use the "observed" map 1980-2016 from Beck et al. 2018 for all occurrences after 2000.
Or
- Use the "observed" map 1980-2016 from Beck et al. 2018 for occurrences from 2001 to 2016, and use a "future" map 2001-2025 from Rubel & Kottek 2010 for occurrences from 2017 to 2021.

There are several scenarios to these future maps in Rubel & Kottek 2010 depending on economy, technology and energy use: A1FI, A2, B1 and B2.

The 2071-2100 "future" map from Beck et al 2018 is based on the RCP8.5 scenario ( = high emissions), so I think it corresponds roughly to the A1FI scenario of Rubel & Kottek 2010 ( = quick economic and technological growth through intensive use of fossil fuel).

Does this seem consistent to you?
What do you think?

**Comment by SanderDevisscher** [comment]
@RomainWilleput Both approaches are doable. However the first approach is by far the easiest => lower complexity = less chance for mistakes. The choice is up to you. 

> There are several scenarios to these future maps in Rubel & Kottek 2010 depending on economy, technology and energy use: A1FI, A2, B1 and B2.

Once I have the reworked the flow It should be no problem to add/remove scenarios as long as they have clear naming ea jjjj-jjjj-scenariocode.

Finaly I have a question: To check if the results of the cm make sense I need a translation, in the form of a legend preferably, for the gridcodes. Can you provide this ?

**Comment by RomainWilleput** [comment]
I also think that the first possibility is the simplest and will not cause any problems for the missing 5 years. That's OK with me!

However, I don't quite understand what you want me to do with the translation you are talking about. I am not yet familiar with terms like gridcodes. Could you please explain in more detail?

**Comment by RomainWilleput** [comment]
I think this is what you need :
11 ... Af
12 ... Am
13 ... As
14 ... Aw
21 ... BWk
22 ... BWh
26 ... BSk
27 ... BSh
31 ... Cfa
32 ... Cfb
33 ... Cfc
34 ... Csa
35 ... Csb
36 ... Csc
37 ... Cwa
38 ... Cwb
39 ... Cwc
41 ... Dfa
42 ... Dfb
43 ... Dfc
44 ... Dfd
45 ... Dsa
46 ... Dsb
47 ... Dsc
48 ... Dsd
49 ... Dwa
50 ... Dwb
51 ... Dwc
52 ... Dwd
61 ... EF
62 ... ET

Is it ?

**Comment by SanderDevisscher** [comment]
Definitely looks like it.
