### ISSUE TITLE
Update riparias Baseline 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/riparias-prep#27]
See https://github.com/inbo/fis-projecten/issues/136

**Comment by timadriaens** [comment]
Apparently we forgot the baseline data for marbled crayfish (Procambarus virginalis) which occurs in Kessel-Lo and Leuven! So this species need to be included. @SanderDevisscher can you see if it is in the baseline data? They should be since all is on gbif (key: 9442269). Can you rerun?

**Comment by timadriaens** [comment]
can you also check whether Porcambarus cf. acutus/zonangulus should be on the map, they are now all target species for RIPARIAS. described in Kevin's paper ([link](https://www.reabic.net/journals/bir/2020/3/BIR_2020_Scheers_etal.pdf)). And on gbif:

https://www.gbif.org/fr/occurrence/1570648293
https://waarnemingen.be/observation/77795720/

**Comment by SanderDevisscher** [comment]
do you mean this species ? 2227289

**Comment by timadriaens** [comment]
yep, that's the one! We should include it in the download (actually we could download all species of the genus Procambarus 2227127 but I don't think there are any more :-)).

**Comment by SanderDevisscher** [comment]
> Apparently we forgot the baseline data for marbled crayfish (Procambarus virginalis) which occurs in Kessel-Lo and Leuven! So this species need to be included. @SanderDevisscher can you see if it is in the baseline data? They should be since all is on gbif (key: 9442269). Can you rerun?

Same as other species

**Comment by SanderDevisscher** [comment]
> yep, that's the one! We should include it in the download (actually we could download all species of the genus Procambarus 2227127 but I don't think there are any more :-)).

I still have to filter after the download. Also I noticed observations after 01/03/2021 were not included. Should be fixed now.
