### ISSUE TITLE
updated baseline check

### ISSUE THREAD

**Issue by timadriaens** [inbo/riparias-prep#32]
@adrienlatli checked the updated baseline (which now looks good for the crayfish spp.):

- [ ] some points have disappeared from the last baseline (in red on the map) (+/-20) only in Flanders. It 's mainly plant observations like ludwigia or hydrocotyle. These need to be checked why they disappeared from the baseline.
- [ ] new observations of this year (2021) have been added. These can be visible on the map but need to be separated from the baseline as this only takes into account the observations made until December 31, 2020.
 
For Wallonia the baseline is OK and validated.
@SanderDevisscher can we check and solve these issues?

![image003](https://user-images.githubusercontent.com/16116743/126995660-85896df9-d9ae-40b2-888c-46512c8ae396.jpg)

**Comment by adrienlatli** [comment]
Hello Sander,

Tell me how i can help you for solving this problem.
Previously, I compared with Arcgis the last baseline send by Tim (in red on the map) with the new one (purple).
Some points disappeared. Do you have the same issue if you create the map in R without XY transformation ?

**Comment by SanderDevisscher** [comment]
> * new observations of this year (2021) have been added. These can be visible on the map but need to be separated from the baseline as this only takes into account the observations made until December 31, 2020.

And thus be excluded from the export (csv/shp) ?

**Comment by SanderDevisscher** [comment]
> [ ] some points have disappeared from the last baseline (in red on the map) (+/-20) only in Flanders. It 's mainly plant observations like ludwigia or hydrocotyle. These need to be checked why they disappeared from the baseline.

We will have to look back into the History of the shapefiles to see which records are "missing". The History can be found here: 
https://github.com/inbo/riparias-prep/commits/master/data/spatial/baseline/t2_ALL_points_Batch2_1_3.dbf

**Comment by SanderDevisscher** [comment]
> Hello Sander,
> 
> Tell me how i can help you for solving this problem.
> Previously, I compared with Arcgis the last baseline send by Tim (in red on the map) with the new one (purple).
> Some points disappeared. Do you have the same issue if you create the map in R without XY transformation ?

@adrienlatli Can you somehow identify the missing records ? By ID perhaps ?

**Comment by adrienlatli** [comment]
Hello Sander,

Find below a datafiles with observations that have disappear in the new baseline (essentially VMM observations) :
[Missing_point_in_new_baseline.txt](https://github.com/inbo/riparias-prep/files/6938102/Missing_point_in_new_baseline.txt)


And find below another data file with the most recent observations that were missing in the last baseline:
[Adding_point_in_new_baseline.txt](https://github.com/inbo/riparias-prep/files/6938103/Adding_point_in_new_baseline.txt)
We found successfully the procambarus sp. observations and plant observations from Natagora in 2021 and the end of 2020.

For the baseline, missing observations from VMM  should appear, also  with observations from the other data owners, up to 2020. But observations after December 31, 2020 should be deleted.

**Comment by SanderDevisscher** [comment]
> Find below a datafiles with observations that have disappear in the new baseline (essentially VMM observations) :
> Missing_point_in_new_baseline.txt

I'll look into what went wrong with this data.  

> And find below another data file with the most recent observations that were missing in the last baseline:
> Adding_point_in_new_baseline.txt
> We found successfully the procambarus sp. observations and plant observations from Natagora in 2021 and the end of 2020.

This is logical since I did not receive any new Walloon data besides the data that's present on gbif. 

> For the baseline, missing observations from VMM should appear, also with observations from the other data owners, up to 2020. But observations after December 31, 2020 should be deleted.

Since I also need the data for the website https://iasspeciesdashboard.shinyapps.io/Riparias-baseline-maps/ I'll have to look into were I can implement this filter.

**Comment by SanderDevisscher** [comment]
I've Identified the step in the flow where the error does occur. I'll see what goes wrong and try to fix it.

**Comment by SanderDevisscher** [comment]
I've fixed the cause for the missing data but I'm waiting for a response whether or not to include the natagora data as demna or as independent to complete the update.

**Comment by adrienlatli** [comment]
> This is logical since I did not receive any new Walloon data besides the data that's present on gbif. Can/may I consider this as a part of the Demna dataflow ? or should I create a new dataflow for Natagora data ?
> 

In my opinion, you have to create a new dataflow for natagora data but only for observations in Flanders. Observations made by Natagora in Wallonia will appear in the DEMNA database when we make data aggregation.

**Comment by SanderDevisscher** [comment]
The Natagora data is all present on gbif so they should be present in the baseline.

**Comment by adrienlatli** [comment]
Hello Sander,

The link with the validated observations:
https://waarnemingen.be/species/8887/maps/?start_date=2010-01-01&interval=15552000&end_date=2020-01-01&only_approved=on&map_type=grid10k

We have less observations than previously but many of them are in the Riparias area but not in the baseline.

**Comment by SanderDevisscher** [comment]
@adrienlatli can you confirm these observation are included in the [waarnemingen.be dataset on gbif](https://www.gbif.org/dataset/9a0b66df-7535-4f28-9f4e-5bc11b8b096c)  ? 

ifso some gbifid's to troubleshoot would be appreciated

**Comment by adrienlatli** [comment]
@SanderDevisscher 
I'have not checked all the crayfish data, but I found at least 1 observation of faxonius limosus included in the 2 datasets  (waarnemingen dataset : https://waarnemingen.be/observation/173441526/  and in the gbif "waarnemingen dataset": https://www.gbif.org/occurrence/2274200746).

**Comment by SanderDevisscher** [comment]
@adrienlatli thanks for the examples. I'll look into what goes wrong.

**Comment by SanderDevisscher** [comment]
I found the suspected cause of the missing _Faxonius limosus_ observations. Somehow the species was not included in the gbif download and thus no waarnemingen.be data was included. I'll look into a fix.

**Comment by SanderDevisscher** [comment]
@adrienlatli [_Orconectes limosus_](https://www.gbif.org/species/2227000) was included in the download but the waarnemingen.be data uses _Faxonius limosus_ and was thus omited. I'll change the download to include both taxa.

**Comment by adrienlatli** [comment]
@SanderDevisscher : Thanks a lot for your work.
Just a small question, for the GBIF download you automatically did not take into account all the names (synonyms and basionyms) of each taxa ?
For examples, orconectes limosus = faxonius limosus = astacus limosus...

**Comment by SanderDevisscher** [comment]
> Just a small question, for the GBIF download you automatically did not take into account all the names (synonyms and basionyms) of each taxa ?
> For examples, orconectes limosus = faxonius limosus = astacus limosus...

It does download synonyms when you download the accepted species, in this case _Faxonius limosus_. The download considers all (including orconectes & astacus) as Faxonius.  When you download only the synonym, like we did, the download gets limited to that synonym.

**Comment by timadriaens** [comment]
the usual hassle with taxonomic matching to the gbif backbone. It will be so much easier when we have published the RIPARIAS target species checklist and the Union List as checklists on gbif (work in progress).

**Comment by SanderDevisscher** [comment]
@adrienlatli is this more in line with what it should be ? 
![image](https://user-images.githubusercontent.com/16779320/155730027-3a3de2c2-aed2-4432-aa30-91409cc32707.png)

**Comment by SanderDevisscher** [comment]
I checked and the example you provided is now present in the baseline

**Comment by adrienlatli** [comment]
Looks great Sander. It 's ok for me :-)
