### ISSUE TITLE
Climate Matching for Procambarus acutus ?

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/riparias-prep#39]
### Discussed in https://github.com/inbo/riparias-prep/discussions/31

<div type='discussions-op-text'>

<sup>Originally posted by **RomainWilleput** June 30, 2021</sup>
Hello @SanderDevisscher 
I know that _Procambarus acutus_ is already established in Belgium, but is it possible to put this species in the Climate Matching analysis ?
_Procambarus acutus_ is available on the belgian pet trade, and in order to present detailed results, I would like to have the values and climatic zones for this species.
Thank you in advance,
Romain</div>

**Comment by SanderDevisscher** [comment]
@RomainWilleput can you provide the gbif keys of these species?

**Comment by SanderDevisscher** [comment]
Thx I'll look into it

**Comment by RomainWilleput** [comment]
Thank you !

**Comment by SanderDevisscher** [comment]
do you need the maps ?

**Comment by RomainWilleput** [comment]
A table with "classification", "n_climate", "n_totaal" and "perc_climate" is enough.
