### ISSUE TITLE
Add trend analysis to RIPARIAS dashboard

### ISSUE THREAD

**Issue by timadriaens** [inbo/riparias-prep#42]
based on cubes and TrIAS time series analysis, present another tab in the RIPARIAS indicator dashboard displaying the TrIAS indicators trend in observations and trend in occupancy at river basin unit.

**Comment by SanderDevisscher** [comment]
These graphs:
Observations
Observations - corrected
Occupancy 
Occupancy - corrected

**Comment by SanderDevisscher** [comment]
https://github.com/inbo/riparias-prep/blob/7d36f452d7c944e71d5c4a751ce73d9c22dc95ea/scripts/shinyapp/baseline_maps_ui_D1.R#L79-L94

**Comment by SanderDevisscher** [comment]
@jrhillae I've created a `trends_prep.r` script which creates/updates `data\interim\trends_compact.csv`. The next step would be to integrate the graphs into the shiny app. Can you share where you want the code for the graphs and what would be the user input parameters ? 

I've created the `42_add_trends`-branch, after I've created the trends_prep script, to integrate the graphs. I'll do a PR into the `41_extending_baseline_map` - branch when I'm ready.

**Comment by SanderDevisscher** [comment]
@jrhillae heads up in heb eindelijk een gat in mijn schema gevonden, ik zal deze namiddag (en mogelijk morgenvoormiddag) werken aan deze issue.

**Comment by jrhillae** [comment]
@SanderDevisscher : I want to check your code but I have trouble installing the trias package. I get the message that it is not available for my version of R. How can I install the trias package?

**Comment by SanderDevisscher** [comment]
@jrhillea have you tried 'devtools::install_github("trias-project/trias")'?

Op zo 17 apr. 2022 07:35 schreef jrhillae ***@***.***>:

**Comment by jrhillae** [comment]
@SanderDevisscher : I tried to install it again and it worked :). The figures are looking ver good! One thing I noticed, the title of the figures is not completely shown. Maybe shorten it by removing species name? The species is very clair from the context (i.e. the one selected on the left) so not necesaary to show in the title. Would that be possible?
