### ISSUE TITLE
colour coding of RBSUs according to level of invasion

### ISSUE THREAD

**Issue by timadriaens** [inbo/riparias-prep#43]
After our meeting today we have an additional idea to track progress in the project in a clear map @damianooldoni. We propose a colour coding at RBSU level based on the level of invasion:

- heavily invaded
- weakly invaded
- scattered occurrences only
- uninvaded
- no data

**Comment by jrhillae** [comment]
@timadriaens: This is an extra tab called 'level of invasion'? Are the categories based on number of observations or occupancy? Maybe using relative occupancy is very intuitive for this?

0% -> uninvaded

0% -> 10% : scattered occurences only

10% -> 30 % weakly invaded

>30% heavily invaded

Currently, maximum relative occupancy is 40% (but I should check again to be sure)

**Comment by timadriaens** [comment]
Indeed, I would make it into an extra tab for clarity, called "Level of invasion" showing a colour code per RBSU for relative occupancy (% grid cells in the RBSU that have at least one observation). I like your proposal, let's start with that. Of course, for some species like Impatiens it will work well, others that have more clustered occurrence invasion levels might be high locally whilst being in a lower category at RBSU level. So maybe in time we could think of combining number of observations and occupancy.

In terms of visualisation, I think the map could show the utm grid and the occurrences. This would give the user also an indication of where in the RBSU the levels of invasion are highest.
