### ISSUE TITLE
Prioritizing management of water bodies in Riparias

### ISSUE THREAD

**Issue by jrhillae** [inbo/riparias-prep#44]
@bramdhondt : by which date do you want a first draft of the script? I only have time to write a first version but you will further elaborate/explore it?

**Comment by jrhillae** [comment]
@bramdhondt: In [this file](https://github.com/inbo/riparias-prep/blob/44_prioritizing/scripts/ad%20hoc/prioritizing%20areas/example.R) you can see the starter of the code to prioritize areas of management within Riparias. 

I read in all data of the different areas (which were all delivered in different formats) and also transformed them to the correct projection. Currently, I am stuck in the intersect as the RAM memory on my laptop is too low. (Misschien eerst een overlay doen met watervlakken en Riparias gebied ook zodat die laag kleiner wordt?  Alle observaties zijn enkel in Riparias gebied momenteel.) 

Veel succes :)

**Comment by timadriaens** [comment]
This was the idea of the analysis:

- produce a map for the entire project area with ponds: use the [INBO watervlakkenkaart](https://www.geopunt.be/catalogus/datasetfolder/10e87ad3-8235-40e0-8269-42c3c96a884d) for Flanders, plans d'eau for Wallonia
- overlay with occurrences of baseline distribution in RIPARIAS project area (probably best to take a buffer around the water bodies)

Looks like you made a great effort already.

I feel it would be nice to integrate this in the dashboard in the surveillance tab (cf. the degree of invasion maps) : 2 maps of the area (baseline-current) showing the ponds in the area, and colour scheming them à rato of the number of alien species observed there? This way, we could show the extra surveillance effort in ponds. Maybe this integration would actually also allow us to recycle some code?

**Comment by bramdhondt** [comment]
@timadriaens and @jrhillae 

@jrhillae : I copied your code into a `Rmd` file (`pond_prioritisation.Rmd`). It already runs well for Flanders: I extracted a list of ponds with the RIPARIAS species! I'll try to improve it further in the coming day(s). I will then respond to Etienne myself.

@timadriaens : I suggest to take a two-phase approach.

- First, to let the script do the bare minimum, i.e. come up with three tables of ponds with historical records of species (one per region). This should allow our partners to go to their next step(s). The reason to do it per region, is that we avoid (cumbersome) steps to align the different geographical input from them. Time frame: coming weeks.
- Second, make it more fancy (e.g. maps) and maybe include it in the D1 dashboard. Time frame: coming months.

**Comment by timadriaens** [comment]
sounds great @bramdhondt

**Comment by bramdhondt** [comment]
@SanderDevisscher (FYI: @jrhillae )

Het script `pond_prioritisation.Rmd` lijst de Vlaamse, Waalse en Brusselse waterlichamen (geïsoleerde wateren) op waarin RIPARIAS-soorten zijn vastgesteld. Voor de soorten en hun _occurrences_ wordt beroep gedaan op het reeds bestaande _current_state.geojson_ (en _baseline.geojson_). Die bevat 14 soorten, en is daarmee niet conform de laatste RIPARIAS-lijst. Zie de link naar de laatste lijst (op GBIF), en ook een opmerking hierover door Damiano, in [issue 50](https://github.com/inbo/riparias-prep/issues/50).

Zou het mogelijk zijn de beide geojson-bestanden conform de laatste lijst op te maken, of de soorten op andere wijze in `pond_prioritisation.Rmd` in te werken? (Merk op: ik heb geen zicht op welke locaties de geojson-bestanden nog worden aangesproken, en of er zich dus conflicten zouden voordien.)

- [ ] uitbreiding script naar alle RIPARIAS-soorten

Ik heb ook problemen met `read_sf` voor WFS (hier voor Brussel; maar plots ook in mijn scripts elders, die eerder wel functioneerden). De [url](https://wfs.environnement.brussels/belb?service=wfs&version=2.0.0&request=GetFeature&typename=BELB%3Awater_polygon) ziet er goed uit, maar `read_sf` krijgt ze niet geopend ("The file doesn't seem to exist"). Moest je hier een oplossing zien...

**Comment by jrhillae** [comment]
@bramdhondt :  Good job! I am happy you succeeded in running the intersect function.

**Comment by bramdhondt** [comment]
@SanderDevisscher (FYI: @jrhillae ) : ik geraak verloren in de verwijzingen naar de easin-repo. Het is me dan ook niet duidelijk hoe het input-bestand _current_state.geojson_ nu uitgebreid moet worden naar alle soorten van de [RIPARIAS](https://www.gbif.org/dataset/fd004d9a-2ea4-4244-bb60-0df508d20a15)-lijst.

**Comment by SanderDevisscher** [comment]
@bramdhondt ik was bij het toevoegen van de RIPARIAS soorten op een foutje gestoten in de taxonomie (zie [issue 17](https://github.com/riparias/riparias-target-list/issues/17)) het is me na het oplossen van deze issue echter niet gelukt om de flow opnieuw te laten lopen. Ik zal dat asap doen.
