### ISSUE TITLE
Improve layers for RBSU and RBU for Riparias dashboard

### ISSUE THREAD

**Issue by jrhillae** [inbo/riparias-prep#58]
Currently, layer for RBU and RBSU do not overlap well. Apparently, RBU layer is at a lower resolution than the RBSU layer. This results in contradictory results when observations are intersected with these layers.

@jrhillae: check if layers in shared Riparias GIS folder are more appropriate to use.

(@SanderDevisscher : ter info)

![image](https://user-images.githubusercontent.com/35692395/203957943-90e33e38-f08a-46bc-8c92-8a5378de7549.png)

green line: RBU, black line: RBSU

**Comment by jrhillae** [comment]
https://drive.google.com/drive/folders/1OnjoMvOECsokz299VccE85iqKxRpqYhc

**Comment by jrhillae** [comment]
@SanderDevisscher : I created a new layer at river basin level (RBU) based on the layer at river basin subunit level (RBSU) due to the issue described above. You can find the script that I used [here](https://github.com/inbo/riparias-prep/blob/166f5cbfad02e9f0fae7f3df37dfb7ca6dc10c12/scripts/shinyapp/compare_maps_riparias.Rmd) and the final layer [here](https://github.com/inbo/riparias-prep/blob/50_add_species/data/spatial/Riparias_subunits/RBU_RIPARIAS_12_02_2021.geojson). As you see, there are very minor holes within each RBU. This is not a very big issue but if you have ideas on how to solve this, they are always welcome! Thank you for reviewing this :)

**Comment by SanderDevisscher** [comment]
PR?

**Comment by jrhillae** [comment]
Niet als deel van PR want ik heb al heel veel gewijzigd op deze branch en moet nog veel veranderen. Liefst enkel het script waar ik naar verwijs hierboven.

**Comment by SanderDevisscher** [comment]
Ok zal er sebiet eens naar kijken, nog ff iets afwerken

**Comment by SanderDevisscher** [comment]
@jrhillae je script ziet er goed uit en lijkt te doen wat je wilt. Weliswaar als je de libraries `rgdal` en `dplyr` inleest.  
Je kan `rgdal` eventueel omzeilen door het EPSG nummer (wgs84 = 4326) te gebruiken ipv de CRS string.
