### ISSUE TITLE
Need for species selectors at site monitoring tab ?

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/riparias-prep#63]
Currently there are some species selectors for the site monitoring graphs but these seem to do nothing at all.  

![image](https://user-images.githubusercontent.com/16779320/226557912-8615b93a-7344-4644-94ea-82535f43dcbd.png)

This is not a breaking issue but I think its best to remove either the selectors or make them influence the graphs when you have an opening.

**Comment by jrhillae** [comment]
@SanderDevisscher : You mean the site-level monitoring tab? That is normal. It is for now only filled with dummy data.

I will make that dependend on the GBIF download the upcoming days :).

**Comment by SanderDevisscher** [comment]
ok fine I'll close this issue then
