### ISSUE TITLE
Determine a logical gbif records threshold

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/riparias-prep#7]
In the current climate matching outputs (see [future](https://github.com/inbo/riparias-prep/blob/a1f20d61681c3941b1858b38b2b29c4339571b92/data/output/data_overlay_future_10km.csv) & [present](https://github.com/inbo/riparias-prep/blob/a1f20d61681c3941b1858b38b2b29c4339571b92/data/output/data_overlay_present_10km.csv) - data overlays) contain all species with at least 1 record in the belgian climate zones (Cfa, Cfb & Dfb). A single/low number of record(s) can be an error, fluke, etc.... and can best be excluded from the list. 

But a what number do we place the threshold ?

**Comment by timadriaens** [comment]
OK, I played around a bit with those. My proposal for criterium:

- minimum number of occurrence records of the species on gbif (`n_totaal`): >=100
- degree of overlap (in %) with Belgian climate: >=10% 

This should leave the following number of species:

- current climate: 18 species

species | Classification | n_totaal | %
-- | -- | -- | --
Astacopsis gouldi | Cfb | 713 | 99
Austropotamobius pallipes | Cfb | 8222 | 94
Austropotamobius torrentium | Dfb | 410 | 96
Cambarus robustus | Dfb | 355 | 54
Cherax destructor | Cfb | 1410 | 43
Creaserinus fodiens | Dfb | 147 | 16
Engaeus granulatus | Cfb | 140 | 14
Euastacus armatus | Cfb | 396 | 47
Euastacus kershawi | Cfb | 219 | 99
Euastacus spinifer | Cfb | 190 | 53
Euastacus sulcatus | Cfb | 118 | 25
Euastacus yarraensis | Cfb | 173 | 94
Faxonius immunis | Dfb | 154 | 53
Faxonius propinquus | Dfb | 344 | 62
Faxonius rusticus | Dfb | 169 | 17
Faxonius virilis | Dfb | 615 | 39
Paranephrops planifrons | Cfb | 263 | 100
Spinastacoides inermis | Cfb | 192 | 93

- future climate: 27 species

species | Classification | n_totaal | %
-- | -- | -- | --
Astacopsis gouldi | Cfb | 713 | 81
Austropotamobius torrentium | Cfa | 410 | 91
Cambaroides similis | Cfa | 156 | 19
Cambarus acuminatus | Cfa | 211 | 100
Cambarus hobbsorum | Cfa | 317 | 100
Cambarus latimanus | Cfa | 929 | 100
Cambarus longulus | Cfa | 147 | 100
Cambarus robustus | Cfa | 355 | 83
Cambarus striatus | Cfa | 487 | 100
Cambarus tenebrosus | Cfa | 158 | 100
Cherax destructor | Cfa | 1410 | 33
Creaserinus fodiens | Cfa | 147 | 91
Euastacus armatus | Cfa | 396 | 51
Euastacus kershawi | Cfa | 219 | 45
Euastacus spinifer | Cfa | 190 | 95
Euastacus sulcatus | Cfa | 118 | 98
Euastacus yarraensis | Cfb | 173 | 35
Faxonius immunis | Cfa | 154 | 66
Faxonius propinquus | Cfa | 344 | 39
Faxonius rusticus | Cfa | 169 | 67
Faxonius virilis | Cfa | 615 | 29
Lacunicambarus diogenes | Cfa | 332 | 94
Paranephrops planifrons | Cfa | 263 | 21
Procambarus gracilis | Cfa | 110 | 57
Procambarus spiculifer | Cfa | 291 | 100
Procambarus versutus | Cfa | 175 | 100
Spinastacoides inermis | Cfb | 192 | 100

- current and future together: 16 species are common to both groups

species | n_totaal | current | future
-- | -- | -- | --
Astacopsis gouldi | 713 | Cfb | Cfb
Austropotamobius torrentium | 410 | Dfb | Cfa
Cambarus robustus | 355 | Dfb | Cfa
Cherax destructor | 1410 | Cfb | Cfa
Creaserinus fodiens | 147 | Dfb | Cfa
Euastacus armatus | 396 | Cfb | Cfa
Euastacus kershawi | 219 | Cfb | Cfa
Euastacus spinifer | 190 | Cfb | Cfa
Euastacus sulcatus | 118 | Cfb | Cfa
Euastacus yarraensis | 173 | Cfb | Cfb
Faxonius immunis | 154 | Dfb | Cfa
Faxonius propinquus | 344 | Dfb | Cfa
Faxonius rusticus | 169 | Dfb | Cfa
Faxonius virilis | 615 | Dfb | Cfa
Paranephrops planifrons | 263 | Cfb | Cfa
Spinastacoides inermis | 192 | Cfb | Cfb

**Comment by timadriaens** [comment]
I find it striking though that none of the species occur twice in both climate classifications for Belgium.

**Comment by timadriaens** [comment]
If we are a bit more severe on the criteria:

>=150 records, 20% overlap

current: 14
future: 22
both: 13 species

>=200 records, 20% overlap

current: 10
future: 15
both: 9 species

@adrienlatli can you take a look at the above list and tell us if that is workable? Do we want to land at around 30 spp to risk assess or do we go for less?

**Comment by adrienlatli** [comment]
Great Job Sander thx.

I think 30 spp to risk assess is realizable by Romain.  This number could be improve if they find new species in shop but I'm think it's still feasible. 
I need to present these results to Romain and Etienne and I will come back soon.

@timadriaens : If you can add Romain to Github it's must be usefull :-) (WILLEPUT  Romain <Romain.Willeput@ulb.be>)

**Comment by timadriaens** [comment]
ok! we need his github name for that

**Comment by timadriaens** [comment]
@adrienlatli OK, calculating back from those 30 species I propose the following cut-offs (it appears the total number of records on gbif is more limiting than the degree of KG overlap):

- [ ] `n_totaal` >= 90
- [ ] `perc_climate` >= 0.20

This leaves exactly 30 species.


species
--
Astacopsis franklinii
Astacopsis gouldi
Austropotamobius torrentium
Cambarus acuminatus
Cambarus bartonii
Cambarus hobbsorum
Cambarus latimanus
Cambarus longirostris
Cambarus longulus
Cambarus robustus
Cambarus striatus
Cambarus tenebrosus
Cherax destructor
Creaserinus fodiens
Euastacus armatus
Euastacus kershawi
Euastacus spinifer
Euastacus sulcatus
Euastacus yarraensis
Faxonius immunis
Faxonius palmeri
Faxonius propinquus
Faxonius rusticus
Faxonius virilis
Lacunicambarus diogenes
Paranephrops planifrons
Procambarus gracilis
Procambarus spiculifer
Procambarus versutus
Spinastacoides inermis



@SanderDevisscher can you rerun using those selection criteria?

**Comment by SanderDevisscher** [comment]
> ok! we need his github name for that

@adrienlatli can you provide his github username ?
