### ISSUE TITLE
Create climate matching flow for the plants

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/riparias-prep#8]
Like for the crayfish a similar flow should be created for the invasive plants. 

@timadriaens is this also @adrienlatli expertise or should I include someone else ? 

The following steps should be undertaken (preferably in order) :
- [x] Create a branch @SanderDevisscher 
- [x] Upload a list of species to be considered @timadriaens + experts
   -  This list should contain the correct gbif taxonkeys => https://docs.google.com/spreadsheets/d/18HNS3HCNbhvTWIn-6iJHQXsPQbfBtOnNZHi7vZRyYDk/edit?usp=sharing
- [x] Copy/Rename crayfish script @SanderDevisscher 
- [x] Rewrite crayfish script without thresholds @SanderDevisscher 
- [x] Determine logical thresholds for plants @timadriaens + experts
- [x] Implement thresholds @SanderDevisscher 
- [x] Rerun script @SanderDevisscher 
- [ ] Create PR @SanderDevisscher 
- [ ] Approve PR @timadriaens + experts

**Comment by adrienlatli** [comment]
@SanderDevisscher : For invasive plants the workflow should be more or less the same. Etienne branquart (SPW) and Antoine Dumortier (student) will drive this study for the SPW.
For the Crayfish, you could invite in Github romain Willput (student), he has created a github account (https://github.com/RomainWilleput)
Thx

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher : For invasive plants the workflow should be more or less the same. Etienne branquart (SPW) and Antoine Dumortier (student) will drive this study for the SPW.

Can you provide the usernames of Etienne & Antoine ?

> For the Crayfish, you could invite in Github romain Willput (student), he has created a github account (https://github.com/RomainWilleput)

@RomainWilleput should have had an invitation for this repo.  

@timadriaens is there a reason why you unassigned us both ? No input is required ?

**Comment by timadriaens** [comment]
@SanderDevisscher no, I made a mistake probably while trying to assign Romain :-)

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher no, I made a mistake probably while trying to assign Romain :-)

Ok I'll reassign us both. 
Before we can assign Romain (or Etienne & Antoine for that matter) to a issue they first need to accept the invitation.

**Comment by adrienlatli** [comment]
The github account of Antoine : https://github.com/Andumort

**Comment by SanderDevisscher** [comment]
> The github account of Antoine : https://github.com/Andumort

He has received an invitation

**Comment by SanderDevisscher** [comment]
Can someone provide me with a white-list ? Or at least the families of plants I should investigate?

**Comment by Andumort** [comment]
Hi @SanderDevisscher,
Here is the Google Sheet link of the plant species list that I made from the catalogs of several Belgian, French, German and Dutch wholesalers :

https://docs.google.com/spreadsheets/d/18HNS3HCNbhvTWIn-6iJHQXsPQbfBtOnNZHi7vZRyYDk/edit?usp=sharing  

There is a column with the GBIF name and one with the GBIF taxon ID (**if available**).
Let me know if you have access to it.

**Comment by Andumort** [comment]
Ups I did not allow access to all, this one should work :

https://docs.google.com/spreadsheets/d/18HNS3HCNbhvTWIn-6iJHQXsPQbfBtOnNZHi7vZRyYDk/edit?usp=sharing

**Comment by SanderDevisscher** [comment]
@Andumort I can access the file. Just a few questions:

1. Can you give a header to every column (see D)? 
2. Can you rename column E to taxonKey ?
3. w'll be limited to those species which have a taxonKey for the climate matching (default and most robust way to download data), is this a problem ?

**Comment by SanderDevisscher** [comment]
`8_plants_cm` - branch

**Comment by SanderDevisscher** [comment]
gbif download using taxonKeys in gsheet 
![image](https://user-images.githubusercontent.com/16779320/115350424-61fc2880-a1b5-11eb-9a5f-909badfecbf4.png)

63 species introduced in Belgium and 190 species not yet introduced

**Comment by SanderDevisscher** [comment]
Without thresholds the climate matching results in [143 species](https://github.com/inbo/riparias-prep/blob/8_plants_cm/data/output/plants_data_overlay_future_10km_white-list.csv) for the future scenario & [121 species](https://github.com/inbo/riparias-prep/blob/8_plants_cm/data/output/plants_data_overlay_present_10km_white-list.csv) for the current one.

Its up to you guys now to determine logical thresholds.

**Comment by Andumort** [comment]
Hello @SanderDevisscher,

As Romain just tell you, the CM script looks good. You can use the same one for plants. 

We finally managed to get the missing taxonKey. Could you rerun the CM with this final list (wich have the same link as before) : https://docs.google.com/spreadsheets/d/18HNS3HCNbhvTWIn-6iJHQXsPQbfBtOnNZHi7vZRyYDk/edit?usp=sharing 

As for Crayfish, could you send me the entire list of the results, with the total number of occurrences, even for species without maching? In this way everythings will be as transparent as possible for us.

Also, I observed a problem with the species "_Pontederia cordata_", wich is a species that could be a potential candidate for the European List and which have a lot of occurrences in GBIF (Belgium included). This species does not appear in the final results. I think the problem come from the "occurrence statut" on GBIF, wich seems to have a problem with the "present" one. Could you confirm this ? If this is the case, do you see a way to avoid this for other species that might be in the same situation ?  

Thanks a lot for all of this,
Have a nice day,
Antoine

**Comment by SanderDevisscher** [comment]
> We finally managed to get the missing taxonKey. Could you rerun the CM with this final list (wich have the same link as before) : https://docs.google.com/spreadsheets/d/18HNS3HCNbhvTWIn-6iJHQXsPQbfBtOnNZHi7vZRyYDk/edit?usp=sharing

I'll do a rerun soon

**Comment by SanderDevisscher** [comment]
@Andumort These are the unfiltered results from the plants CM

- [plant - taxa from whitelist missing from gbif](https://github.com/inbo/riparias-prep/blob/fadd4bfedde89622666d97e67b25b1f1f2593702/data/interim/plants_missing_from_gbif.csv)
- [unfiltered overlay with climate matching scenarios](https://github.com/inbo/riparias-prep/blob/fadd4bfedde89622666d97e67b25b1f1f2593702/data/interim/plants_data_overlay_white-list_allSpecies.csv)

when using the same thresholds as the Crayfish:

- [current scenario](https://github.com/inbo/riparias-prep/blob/fadd4bfedde89622666d97e67b25b1f1f2593702/data/output/plants_data_overlay_present_10km_white-list.csv)
- [future scenario](https://github.com/inbo/riparias-prep/blob/fadd4bfedde89622666d97e67b25b1f1f2593702/data/output/plants_data_overlay_future_10km_white-list.csv)

**Comment by Andumort** [comment]
Hi @Sander, Thank you for all of this.

We have just discussed with Adrien, Etienne and Romain.
If we are not mistaken, the species which present at least one observation in Belgium are excluded from the analysis? 

We think that we'll not necessarily exclude all the species which present an observation in Belgium.
Could you therefore rerun the analysis with the entirety of the 202 species in the link below :

https://docs.google.com/spreadsheets/d/18HNS3HCNbhvTWIn-6iJHQXsPQbfBtOnNZHi7vZRyYDk/edit?usp=sharing

You can send me the results for all species, without thresholds, we'll fix them ourselves afterwards.

Thank you so much !

**Comment by SanderDevisscher** [comment]
@Andumort I'm currently working on a Trias Package function for climate matching see [#73](https://github.com/trias-project/trias/issues/73) 

This function does not exclude observations made in the specified region (ea Belgium).  Also the unfiltered list of climate matched species is a output. 

When this function is completed I'll use it to rerun the plants cm. 
However I'm currently very busy so its not for any time soon.

**Comment by Andumort** [comment]
Hello @SanderDevisscher,

Do you think that the CM of the missing species (with occurrences in Belgium) can be carried out in the following days?
Indeed, I need the values and climatic zones for these species otherwise I cannot complete the risk analyzes and I will therefore not be able to make a coherent work.

I'm sorry to make this urgent but my master thesis must be returned by August 10 at the latest, which doesn't give me much time to complete the analyzes and the writing.

Link to species with GBIF Taxonkey : https://docs.google.com/spreadsheets/d/18HNS3HCNbhvTWIn-6iJHQXsPQbfBtOnNZHi7vZRyYDk/edit?usp=sharing 

Thank you very much in advance for your work and your response.

**Comment by timadriaens** [comment]
Hi @SanderDevisscher, Antoine and me tried to run the script on his side so he could do the analysis himself but something went wrong on the rgbif side. Furthermore, upon using the scipt on my end with the species Acorus gramineus (gbifkey 2873807) the cm returned an N_total of 50, whereas there are many more records on gbif for this species (despite no filtering was on). We therefore gave up and decided to wait for you :-)

**Comment by SanderDevisscher** [comment]
I'm going to rework this flow to use the new Trias climate matching function.

**Comment by Andumort** [comment]
Ok, thanks.
I just hope that it will not change the results to much compared to the last ones, I do not have much time anymore :/

**Comment by SanderDevisscher** [comment]
https://docs.google.com/spreadsheets/d/18HNS3HCNbhvTWIn-6iJHQXsPQbfBtOnNZHi7vZRyYDk/edit?usp=sharing is still correct ?

**Comment by Andumort** [comment]
Yes !

**Comment by SanderDevisscher** [comment]
@Andumort When filtering on `BasisOfRecord = c("HUMAN_OBSERVATION", "PRESERVED_SPECIMEN", "UNKNOWN")` all records for [Samolus valerandi subsp. parviflorus (Raf.) Hultén](https://www.gbif.org/species/9109321) with coordinates are omited => in the current version this results in an error (which I'll fix). 

Is it correct/preferable to use the species instead of the subspecies? [Samolus valerandi L.](https://www.gbif.org/species/9109321) ?

**Comment by Andumort** [comment]
Hi @SanderDevisscher,

The species Samolus valerandi L. is native to Belgium (therefore eliminated from the species to be analyzed). This is why I had kept the subspecies "Samolus valerandi subsp. parviflorus (Raf.) Hultén" present in the trade in this case.

If the number of georeferenced occurrences is too low with the filters set, the species is considered to have too few occurrences to achieve climate matching and is classified in the "data deficient" list. In the vast majority of cases, the species which have very few occurrences on GBIF are also very poorly documented in the literature, which does not allow for the risk analysis anyway.

So taking the species here is pointless, and if the occurrences are too low for the subspecies, that may be a valid result.

**Comment by SanderDevisscher** [comment]
I've reworked the function so that species without sufficient spatial data are omited from the results.

**Comment by SanderDevisscher** [comment]
I hope to have them by this afternoon

**Comment by Andumort** [comment]
Hi @SanderDevisscher,

Thank you very much ! It looks good for me compared to the last results.

So, if I understood, the new script doesn't eliminate the occurrences < 1950 ?

Could you precise me what are the others change you did, and what are the finals filters/script used, please ? To be sure that I don't say something wrong in my paper. Is it :

- occurrenceStatus = "Present"
- basisOfRecord = "Human observation" + "Preserved specimen" + "Unknown"  ==> Why those specific record only ?
- remove duplicates when a species is spotted on the same day on the same spot
- Combine occurrences of synonyme species with the accepted species

Thanks for your work !

**Comment by SanderDevisscher** [comment]
> So, if I understood, the new script doesn't eliminate the occurrences < 1950 ?

Correct, we now filter occurrences < 1901

> Could you precise me what are the others change you did, and what are the finals filters/script used, please ? To be sure that I don't say something wrong in my paper. Is it :

> occurrenceStatus = "Present"

Yes

> basisOfRecord = "Human observation" + "Preserved specimen" + "Unknown" ==> Why those specific record only ?

Yes, To eliminate records with dubious origin and/or location

> remove duplicates when a species is spotted on the same day on the same spot

Yes

> Combine occurrences of synonyme species with the accepted species

Yes
=> Thresholds are:
number of total records at least 90
percentage of records in Belgian climate zones (future or  present) at least 20% 

Additionally records that have incorrect locations which cause them to be placed outside of a climate zone are omitted. 
Similarly records on the fringes of the climate zones can be omitted due to inaccuracies in the climate zone fineness (km squares) which cause them to fall outside the climate zone. 

Some further considerations: No limits or consideration was placed on the coordinate uncertainty which allows records to be placed in the wrong climate zone.
