### ISSUE TITLE
Update Riparias Baseline

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/riparias-prep#9]
@timadriaens While I wait for new walloon data (now with ID column or in dwc).

I will begin with the part of the flow following the data compilation (done for VMM & GBIF). 
What final form of output do you want ? _(all outputs will be limited to the RIPARIAS project perimeters <sup>1</sup>)_

~- [ ] Map, csv and shapefiles of the 10x10km squares infected by target species.~

- [x] Map, csv and shapefiles of point data of occurrences  

~- [ ] Map, csv and shapefiles of another size of grid (example 1x1km), please specify which.~
~- [ ] None of the above, but ...~

<sup>1</sup> _remember to answer my previous question about the perimeters (see https://github.com/inbo/easin/issues/40#issuecomment-799263746)_

_Originally posted by @SanderDevisscher in https://github.com/inbo/easin/issues/40#issuecomment-802774080_

**Comment by SanderDevisscher** [comment]
I'll create a RMD which outputs .html files with the map

**Comment by timadriaens** [comment]
[reperimeterriparias.zip](https://github.com/inbo/riparias-prep/files/6244146/reperimeterriparias.zip)

**Comment by SanderDevisscher** [comment]
- [ ] Copy merged points shape to [riparias-prep](https://github.com/inbo/riparias-prep) - repo
- [ ] Create .rmd to subset and display points on a map and export this to html

**Comment by SanderDevisscher** [comment]
`9_Create_Riparias_Baseline` - branch

**Comment by SanderDevisscher** [comment]
@timadriaens which language should the page be ? 

also this is the current state: https://iasspeciesdashboard.shinyapps.io/Riparias-baseline-maps/

**Comment by timadriaens** [comment]
Looking ACE! I suggest English will do.

**Comment by timadriaens** [comment]
Would it be possible to include a link to the original record and the data source when you click on the dot?

**Comment by SanderDevisscher** [comment]
> Would it be possible to include a link to the original record and the data source when you click on the dot?

I'll try to implement this
